const schema = {
  tables: [
    {
      name: "api_ordering_institutions",
      columns: [
        {
          name: "patient_id",
          type: "integer",
          fk: { table: "patients", column: "id" },
        },
        {
          name: "institution_id",
          type: "integer",
          fk: { table: "institutions", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 3158.8075219131097, y: 2617.3440741975783 },
    },
    {
      name: "base_permissions",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "action", type: "string" },
        { name: "domain", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "internal_permission", type: "boolean" },
      ],
      pos: { x: 837.3984070651253, y: 3039.0243902439024 },
    },
    {
      name: "batch_uploads",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "content_sha", type: "string" },
        { name: "content_type", type: "string" },
        { name: "content", type: "jsonb" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 5691.74646550781, y: 1509.0136449609372 },
    },
    {
      name: "access_contexts",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "execution_context_id",
          type: "integer",
          fk: { table: "execution_contexts", column: "id" },
        },
        {
          name: "user_roles_user_id",
          type: "integer",
          fk: { table: "user_roles_users", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 2099.729063452744, y: 4376.151827680387 },
    },
    {
      name: "addresses",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "location_name", type: "string" },
        { name: "address_line_1", type: "string" },
        { name: "address_line_2", type: "string" },
        { name: "city", type: "string" },
        { name: "state", type: "string" },
        { name: "postal_code", type: "string" },
        { name: "country", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "type", type: "integer" },
        {
          name: "institution_id",
          type: "integer",
          fk: { table: "institutions", column: "id" },
        },
        { name: "time_zone", type: "string" },
        { name: "is_same", type: "boolean" },
        { name: "instructions_for_courier", type: "string" },
        { name: "default_time_for_courier", type: "string" },
      ],
      pos: { x: 4448.737798344476, y: 3261.2078307443844 },
    },
    {
      name: "attachments",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "type", type: "string" },
        { name: "s3_key", type: "string" },
        { name: "filename", type: "string" },
        { name: "content_type", type: "string" },
        { name: "s3_bucket_name", type: "string" },
        { name: "md5", type: "string" },
        {
          name: "treatment_id",
          type: "integer",
          fk: { table: "treatments", column: "id" },
        },
        {
          name: "procedure_step_id",
          type: "integer",
          fk: { table: "procedure_steps", column: "id" },
        },
        { name: "removed", type: "boolean" },
        {
          name: "template_id",
          type: "integer",
          fk: { table: "templates", column: "id" },
        },
      ],
      pos: { x: 4358.7970537221845, y: 1753.38400036985 },
    },
    {
      name: "business_processes",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "process_key", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 2970.6288506368983, y: 2091.8400199324997 },
    },
    {
      name: "cassettes",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "specimen_id",
          type: "integer",
          fk: { table: "specimens", column: "id" },
        },
        {
          name: "treatment_id",
          type: "integer",
          fk: { table: "treatments", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 5000, y: 2105.685267668106 },
    },
    {
      name: "client_identities",
      columns: [
        { name: "id", type: "uuid", pk: true },
        { name: "wso2_consumer_key", type: "string" },
        { name: "wso2_app_id", type: "string" },
        { name: "active", type: "boolean" },
        { name: "default", type: "boolean" },
        {
          name: "user_id",
          type: "integer",
          fk: { table: "users", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "name", type: "string" },
      ],
      pos: { x: 1368.074436767578, y: 5321.402241943358 },
    },
    {
      name: "coc_event_procedure_steps",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "procedure_step_name", type: "string" },
        { name: "event_type", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 6259.083425507811, y: 1259.3470918359371 },
    },
    {
      name: "courier_configs",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "name", type: "string" },
        { name: "deunicode", type: "boolean" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "billing_center", type: "string" },
        { name: "customer_name", type: "string" },
        { name: "coc_event", type: "boolean" },
        { name: "lead_time", type: "string" },
      ],
      pos: { x: 4590.241241455078, y: 5000 },
    },
    {
      name: "configuration_values",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "key", type: "text" },
        { name: "value", type: "text" },
        { name: "category", type: "text" },
        { name: "default_value", type: "text" },
        { name: "display_name", type: "text" },
        { name: "description", type: "text" },
        { name: "data_type", type: "text" },
        { name: "is_phi", type: "boolean" },
        { name: "is_sensitive", type: "boolean" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 6000.298145507812, y: 1153.8779537109372 },
    },
    {
      name: "execution_context_grants",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "execution_context_permission_id",
          type: "integer",
          fk: { table: "execution_context_permissions", column: "id" },
        },
        {
          name: "role_context_id",
          type: "integer",
          fk: { table: "role_contexts", column: "id" },
        },
        { name: "deleted_at", type: "datetime" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 455.8206366975779, y: 1347.4252985098822 },
    },
    {
      name: "events",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "type", type: "string" },
        { name: "event_details", type: "json" },
        { name: "created_at", type: "datetime" },
        { name: "performed_by", type: "string" },
        { name: "target_model_name", type: "string" },
        { name: "target_model_id_number", type: "integer" },
        { name: "transaction_id", type: "string" },
      ],
      pos: { x: 6256.595105507811, y: 937.5690737109372 },
    },
    {
      name: "contacts",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "name", type: "string" },
        { name: "country_code", type: "string" },
        { name: "phone_number", type: "string" },
        {
          name: "address_id",
          type: "integer",
          fk: { table: "addresses", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 4827.516989501952, y: 3532.183907958983 },
    },
    {
      name: "config_deployments",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "bundle_hash", type: "string" },
        { name: "deployment_id", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "payload", type: "jsonb" },
      ],
      pos: { x: 3312.1891011390585, y: 2829.2618418127545 },
    },
    {
      name: "execution_context_permissions",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "domain", type: "string" },
        { name: "action", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 322.48859353827913, y: 984.2815616266515 },
    },
    {
      name: "execution_contexts_shipment_legs",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "execution_context_id", type: "integer" },
        { name: "shipment_leg_id", type: "integer" },
      ],
      pos: { x: 5935.601825507811, y: 969.8179074609374 },
    },
    {
      name: "infusion_stages",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "treatment_id",
          type: "integer",
          fk: { table: "treatments", column: "id" },
        },
        { name: "estimated_infusion_date", type: "datetime" },
        {
          name: "institution_id",
          type: "integer",
          fk: { table: "institutions", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "order_type", type: "integer" },
      ],
      pos: { x: 4062.868115184753, y: 3861.2426654433175 },
    },
    {
      name: "institution_capabilities",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "is_active", type: "boolean" },
        { name: "has_capacity", type: "boolean" },
        { name: "type", type: "string" },
      ],
      pos: { x: 331.7060517101753, y: 2968.0195051157057 },
    },
    {
      name: "institution_execution_context_capabilities",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "institution_id",
          type: "integer",
          fk: { table: "institutions", column: "id" },
        },
        {
          name: "execution_context_id",
          type: "integer",
          fk: { table: "execution_contexts", column: "id" },
        },
        {
          name: "institution_capability_id",
          type: "integer",
          fk: { table: "institution_capabilities", column: "id" },
        },
        { name: "is_active", type: "boolean" },
        { name: "uuid", type: "uuid" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 81.30073443983952, y: 2396.7417481792004 },
    },
    {
      name: "identity_providers",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "alias_in_keycloak", type: "string" },
        { name: "friendly_name", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "type", type: "integer" },
      ],
      pos: { x: 986.9919691628556, y: 5000 },
    },
    {
      name: "institution_capabilities_types",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "institution_type_id",
          type: "integer",
          fk: { table: "institution_types", column: "id" },
        },
        {
          name: "institution_capability_id",
          type: "integer",
          fk: { table: "institution_capabilities", column: "id" },
        },
      ],
      pos: { x: 601.082745477113, y: 2891.597973169673 },
    },
    {
      name: "indications",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "name", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 143.6314239088436, y: 4394.580144287771 },
    },
    {
      name: "institution_types",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "name", type: "string" },
        { name: "is_active", type: "boolean" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 686.7182041571392, y: 2625.4734153023905 },
    },
    {
      name: "label_scan_values",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "name", type: "string" },
        { name: "value", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "deleted_at", type: "datetime" },
        {
          name: "treatment_id",
          type: "integer",
          fk: { table: "treatments", column: "id" },
        },
        { name: "labelable_type", type: "string" },
        { name: "labelable_id", type: "integer" },
        { name: "type", type: "string" },
      ],
      pos: { x: 5000, y: 2963.1360620017945 },
    },
    {
      name: "label_scan_verifications",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "label_scan_value_id", type: "integer" },
        { name: "invalidated_at", type: "datetime" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "block_id", type: "string" },
        { name: "completed_at", type: "datetime" },
        { name: "procedure_step_id", type: "integer" },
        {
          name: "specimen_id",
          type: "integer",
          fk: { table: "specimens", column: "id" },
        },
        { name: "step_location", type: "string" },
      ],
      pos: { x: 2621.7277316894524, y: 6361.858421630858 },
    },
    {
      name: "institutions_physicians",
      columns: [
        {
          name: "institution_id",
          type: "integer",
          fk: { table: "institutions", column: "id" },
        },
        {
          name: "physician_id",
          type: "integer",
          fk: { table: "physicians", column: "id" },
        },
      ],
      pos: { x: 5006.900454345702, y: 3989.4716228027332 },
    },
    {
      name: "institutions_users",
      columns: [
        {
          name: "institution_id",
          type: "integer",
          fk: { table: "institutions", column: "id" },
        },
        {
          name: "user_id",
          type: "integer",
          fk: { table: "users", column: "id" },
        },
      ],
      pos: { x: 2310.177753632812, y: 4748.673318398436 },
    },
    {
      name: "label_definitions",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "therapy_id",
          type: "integer",
          fk: { table: "therapies", column: "id" },
        },
        { name: "name", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        {
          name: "business_process_id",
          type: "integer",
          fk: { table: "business_processes", column: "id" },
        },
        { name: "legacy_procedure_config_reference", type: "integer" },
      ],
      pos: { x: 1840.3313840332028, y: 1478.149837646484 },
    },
    {
      name: "languages",
      columns: [
        { name: "locale", type: "string", pk: true },
        { name: "short_name", type: "string" },
        { name: "full_name", type: "string" },
        { name: "enabled", type: "boolean" },
        { name: "default", type: "boolean" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 5711.6530255078105, y: 998.2251390234371 },
    },
    {
      name: "manufacturing_status_definitions",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "name", type: "string" },
        { name: "position", type: "integer" },
        {
          name: "execution_context_id",
          type: "integer",
          fk: { table: "execution_contexts", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 1689.9689134220444, y: 3050.9400406504064 },
    },
    {
      name: "manufacturing_statuses",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "started_at", type: "datetime" },
        { name: "confirmed", type: "boolean" },
        {
          name: "manufacturing_status_definition_id",
          type: "integer",
          fk: { table: "manufacturing_status_definitions", column: "id" },
        },
        {
          name: "manufacturing_run_id",
          type: "integer",
          fk: { table: "manufacturing_runs", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 1262.868940151804, y: 2988.068172795986 },
    },
    {
      name: "manufacturing_capacities",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "capacity_date", type: "date" },
        { name: "capacity", type: "integer" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        {
          name: "institution_id",
          type: "integer",
          fk: { table: "institutions", column: "id" },
        },
      ],
      pos: { x: 3294.3008050685976, y: 3562.593521076812 },
    },
    {
      name: "manufacturing_runs",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "run_id", type: "string" },
        { name: "lot_number", type: "string" },
        {
          name: "traceability_id",
          type: "integer",
          fk: { table: "traceabilities", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 1351.1328635942766, y: 2490.361286288917 },
    },
    {
      name: "orders",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "treatment_id",
          type: "integer",
          fk: { table: "treatments", column: "id" },
        },
        { name: "date_of_consent", type: "date" },
        {
          name: "prescriber_user_id",
          type: "integer",
          fk: { table: "physicians", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "status", type: "integer" },
      ],
      pos: { x: 5281.173665507811, y: 2713.8431837109365 },
    },
    {
      name: "ost_shipments",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "pending_courier_reschedules_pick_up", type: "integer" },
        { name: "pending_courier_reschedules_delivery", type: "integer" },
        {
          name: "shipment_id",
          type: "integer",
          fk: { table: "shipments", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 2533.3888208203116, y: 4708.833924023436 },
    },
    {
      name: "ost_user_infos",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "dismiss_shipment_error", type: "boolean" },
        {
          name: "treatment_id",
          type: "integer",
          fk: { table: "treatments", column: "id" },
        },
        {
          name: "user_id",
          type: "integer",
          fk: { table: "users", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 4833.173398007811, y: 5333.1377537109365 },
    },
    {
      name: "physicians",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "email", type: "string" },
        { name: "first_name", type: "string" },
        { name: "middle_name", type: "string" },
        { name: "last_name", type: "string" },
        { name: "country_code", type: "string" },
        { name: "phone_number", type: "string" },
        { name: "additional_country_code", type: "string" },
        { name: "additional_phone_number", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "deleted_at", type: "datetime" },
      ],
      pos: { x: 4928.444632346715, y: 2059.61517085874 },
    },
    {
      name: "permitted_reports_objects",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "report_type", type: "string" },
        { name: "object", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "whitelisted_details", type: "json" },
        { name: "blacklisted_details", type: "json" },
        { name: "template", type: "string" },
      ],
      pos: { x: 6199.363745507811, y: 606.9461593359374 },
    },
    {
      name: "phi_fields",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "resource_name", type: "string" },
        { name: "method_name", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 5729.0712655078105, y: 1259.3967549609372 },
    },
    {
      name: "patient_identifiers_deprecated",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "patient_id",
          type: "integer",
          fk: { table: "patients", column: "id" },
        },
        { name: "identifier_type", type: "string" },
        { name: "identifier", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 4744.3011965332025, y: 2481.9383298339835 },
    },
    {
      name: "patients",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "dob", type: "date" },
        { name: "email", type: "string" },
        { name: "phone_number", type: "string" },
        { name: "first_name", type: "string" },
        { name: "middle_name", type: "string" },
        { name: "last_name", type: "string" },
        { name: "initials", type: "string" },
        { name: "gender", type: "string" },
        { name: "biological_sex", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "vineti_core_patient_id", type: "string" },
        { name: "source", type: "integer" },
      ],
      pos: { x: 4365.759350830077, y: 2309.2686892089837 },
    },
    {
      name: "phase_keys",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "key_name", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 3000.4897434082027, y: 1559.113978271484 },
    },
    {
      name: "poly_joins",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "parent_id", type: "integer" },
        { name: "parent_type", type: "string" },
        { name: "child_id", type: "integer" },
        { name: "child_type", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 5450.379425507812, y: 1269.522109335937 },
    },
    {
      name: "procedures",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "type", type: "string" },
        {
          name: "treatment_id",
          type: "integer",
          fk: { table: "treatments", column: "id" },
        },
        { name: "current_step_name", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        {
          name: "custodian_id",
          type: "integer",
          fk: { table: "users", column: "id" },
        },
        { name: "scheduled_start_date", type: "datetime" },
        {
          name: "institution_id",
          type: "integer",
          fk: { table: "institutions", column: "id" },
        },
        { name: "started_at", type: "datetime" },
        { name: "completed_at", type: "datetime" },
        { name: "cancelled_at", type: "datetime" },
        { name: "cancellation_reason", type: "string" },
        { name: "status", type: "integer" },
        { name: "process_instance_id", type: "string" },
        {
          name: "procedure_config_id",
          type: "integer",
          fk: { table: "procedure_configs", column: "id" },
        },
        { name: "deleted_at", type: "datetime" },
        { name: "process_vars", type: "jsonb" },
        {
          name: "cancelled_by_id",
          type: "integer",
          fk: { table: "users", column: "id" },
        },
        { name: "item_count", type: "integer" },
        { name: "item_volume", type: "string" },
        { name: "item_expiry_date", type: "date" },
        { name: "cancellation_reason_other_text", type: "string" },
        { name: "subprocesses", type: "jsonb" },
      ],
      pos: { x: 3609.707997226457, y: 4487.765643525576 },
    },
    {
      name: "printers",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "serial_number", type: "string" },
        {
          name: "institution_id",
          type: "integer",
          fk: { table: "institutions", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        {
          name: "label_definition_id",
          type: "integer",
          fk: { table: "label_definitions", column: "id" },
        },
        { name: "height", type: "float" },
        { name: "width", type: "float" },
        { name: "print_density", type: "integer" },
        { name: "print_type", type: "integer" },
        { name: "status", type: "integer" },
      ],
      pos: { x: 2069.995194616704, y: 1906.8237374277107 },
    },
    {
      name: "procedure_configs",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "procedure_type", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "process_definition_id", type: "string" },
        {
          name: "config_deployment_id",
          type: "integer",
          fk: { table: "config_deployments", column: "id" },
        },
        { name: "process_vars", type: "jsonb" },
        { name: "name", type: "string" },
        { name: "configurations", type: "jsonb" },
        {
          name: "business_process_id",
          type: "integer",
          fk: { table: "business_processes", column: "id" },
        },
        { name: "checksum", type: "string" },
        { name: "bpmn", type: "text" },
      ],
      pos: { x: 3919.76222423357, y: 2275.8669969512193 },
    },
    {
      name: "product_journeys",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "execution_context_id",
          type: "integer",
          fk: { table: "execution_contexts", column: "id" },
        },
        {
          name: "procedure_config_id",
          type: "integer",
          fk: { table: "procedure_configs", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 3673.1530000846883, y: 2990.7712858866867 },
    },
    {
      name: "shipment_documents",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "shipment_id",
          type: "integer",
          fk: { table: "shipments", column: "id" },
        },
        { name: "type", type: "string" },
        { name: "s3_key", type: "string" },
        { name: "filename", type: "string" },
        { name: "content_type", type: "string" },
        { name: "s3_bucket_name", type: "string" },
        { name: "md5", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 2730.612441065512, y: 4163.124739897607 },
    },
    {
      name: "resource_identifiers",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "resource_id", type: "integer" },
        { name: "resource_type", type: "string" },
        { name: "identifier_type", type: "string" },
        { name: "identifier", type: "string" },
        { name: "deleted_at", type: "datetime" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 5345.86998550781, y: 371.9879026171874 },
    },
    {
      name: "rest_client_logs",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "method", type: "text" },
        { name: "scheme", type: "text" },
        { name: "host", type: "text" },
        { name: "port", type: "integer" },
        { name: "path", type: "text" },
        { name: "query_string", type: "text" },
        { name: "started_at", type: "datetime" },
        { name: "status", type: "integer" },
        { name: "duration", type: "decimal" },
        { name: "request", type: "text" },
        { name: "response", type: "text" },
        { name: "error_type", type: "text" },
        { name: "error_message", type: "text" },
      ],
      pos: { x: 5997.809825507811, y: 1611.229013085937 },
    },
    {
      name: "shipment_legs",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "name", type: "string" },
        { name: "courier", type: "string" },
        { name: "metric", type: "boolean" },
        { name: "commodity", type: "string" },
        { name: "quantity", type: "integer" },
        { name: "width", type: "decimal" },
        { name: "height", type: "decimal" },
        { name: "length", type: "decimal" },
        { name: "weight", type: "decimal" },
        { name: "qualification_time", type: "integer" },
        { name: "package_quantity", type: "integer" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "shipper", type: "string" },
        {
          name: "shipper_institution_id",
          type: "integer",
          fk: { table: "institutions", column: "id" },
        },
        { name: "consignee", type: "string" },
        {
          name: "consignee_institution_id",
          type: "integer",
          fk: { table: "institutions", column: "id" },
        },
        { name: "label_scan_name", type: "string" },
        { name: "temperature", type: "string" },
        { name: "refrigerant", type: "string" },
        { name: "dry_ice_weight", type: "decimal" },
        { name: "commodity_temperature_code", type: "string" },
        { name: "monitor_code", type: "string" },
        { name: "package_model", type: "string" },
        { name: "packaging_code", type: "string" },
        { name: "dropoff_time", type: "string" },
        { name: "dropoff_date", type: "string" },
        { name: "pickup_time", type: "string" },
        { name: "pickup_date", type: "string" },
        { name: "shipper_contact", type: "string" },
        { name: "consignee_contact", type: "string" },
        { name: "shipper_milestone", type: "string" },
        { name: "consignee_milestone", type: "string" },
        { name: "customer_account_number", type: "string" },
        { name: "project_name", type: "string" },
        { name: "reference", type: "string" },
        { name: "notifications", type: "jsonb" },
        {
          name: "courier_config_id",
          type: "integer",
          fk: { table: "courier_configs", column: "id" },
        },
        { name: "service_code", type: "string" },
      ],
      pos: { x: 4171.7934068302475, y: 4611.8978422831715 },
    },
    {
      name: "products",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "name", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "lead_time", type: "integer" },
        { name: "final_product_ship_release", type: "integer" },
        { name: "final_product_pickup", type: "integer" },
        { name: "final_product_delivery", type: "integer" },
      ],
      pos: { x: 173.983003776571, y: 3460.1531072683774 },
    },
    {
      name: "regions",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "name", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 2552.438934536377, y: 1044.7783976521082 },
    },
    {
      name: "signature_documents",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "location", type: "string" },
        { name: "md5", type: "string" },
        { name: "type", type: "string" },
        { name: "meaning", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "cancelled_at", type: "datetime" },
        {
          name: "procedure_step_id",
          type: "integer",
          fk: { table: "procedure_steps", column: "id" },
        },
        { name: "voided_at", type: "datetime" },
        { name: "has_masked_phi_fields", type: "boolean" },
        { name: "pdf_html", type: "string" },
        { name: "signature_document_template_id", type: "integer" },
      ],
      pos: { x: 3274.0996339337175, y: 963.3040901983552 },
    },
    {
      name: "signature_document_templates",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "name", type: "string" },
        { name: "html_body", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "config_deployment_id", type: "integer" },
      ],
      pos: { x: 5649.445025507812, y: 366.74001386718743 },
    },
    {
      name: "signatures",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "user_id",
          type: "integer",
          fk: { table: "users", column: "id" },
        },
        { name: "role", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        {
          name: "signature_document_id",
          type: "integer",
          fk: { table: "signature_documents", column: "id" },
        },
        { name: "voided_at", type: "datetime" },
        { name: "time_zone", type: "string" },
      ],
      pos: { x: 2729.7691936104297, y: 1270.2741489393172 },
    },
    {
      name: "specimens_subprocesses",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "specimen_id",
          type: "integer",
          fk: { table: "specimens", column: "id" },
        },
        {
          name: "subprocess_id",
          type: "integer",
          fk: { table: "subprocesses", column: "id" },
        },
        { name: "state", type: "integer" },
      ],
      pos: { x: 3089.1894317578117, y: 5437.937730585936 },
    },
    {
      name: "shipments",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "tracking_id", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "delivered_at", type: "datetime" },
        { name: "picked_up_at", type: "datetime" },
        { name: "delivery_eta", type: "datetime" },
        { name: "delayed_reason", type: "string" },
        { name: "pick_up_eta", type: "datetime" },
        { name: "pick_up_deadline", type: "datetime" },
        { name: "delivery_deadline", type: "datetime" },
        { name: "cancelled_at", type: "datetime" },
        {
          name: "treatment_id",
          type: "integer",
          fk: { table: "treatments", column: "id" },
        },
        {
          name: "from_institution_id",
          type: "integer",
          fk: { table: "institutions", column: "id" },
        },
        {
          name: "to_institution_id",
          type: "integer",
          fk: { table: "institutions", column: "id" },
        },
        {
          name: "sibling_id",
          type: "integer",
          fk: { table: "shipments", column: "id" },
        },
        { name: "shipping_receipt_checklist", type: "jsonb" },
        {
          name: "shipment_leg_id",
          type: "integer",
          fk: { table: "shipment_legs", column: "id" },
        },
        { name: "product_receipt_checklist", type: "jsonb" },
        { name: "shipping_checklist", type: "jsonb" },
        { name: "order_params", type: "jsonb" },
        { name: "order_status_message", type: "text" },
        { name: "order_updated_at", type: "datetime" },
        { name: "tracking_status_message", type: "text" },
        { name: "tracking_updated_at", type: "datetime" },
        { name: "tracked_at", type: "datetime" },
        { name: "order_cancelled_at", type: "datetime" },
        { name: "notifications", type: "jsonb" },
        {
          name: "subprocess_id",
          type: "integer",
          fk: { table: "subprocesses", column: "id" },
        },
        { name: "order_status", type: "integer" },
        { name: "tracking_status", type: "integer" },
        { name: "temp_tracking_id", type: "string" },
        { name: "cancelled_reason", type: "string" },
      ],
      pos: { x: 3024.909522410654, y: 4337.6376185636855 },
    },
    {
      name: "specimens",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "volume", type: "float" },
        { name: "state", type: "integer" },
        { name: "status", type: "integer" },
        { name: "material", type: "integer" },
        {
          name: "shipment_id",
          type: "integer",
          fk: { table: "shipments", column: "id" },
        },
        {
          name: "treatment_id",
          type: "integer",
          fk: { table: "treatments", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "collected_product_volume", type: "decimal" },
        { name: "anticoagulant_type", type: "string" },
        { name: "anticoagulant_volume", type: "decimal" },
        { name: "pre_collection_label_applied", type: "boolean" },
        { name: "name", type: "string" },
        { name: "product_volume", type: "decimal" },
        { name: "mononuclear_cell_count", type: "decimal" },
        { name: "cell_viability", type: "decimal" },
        { name: "collection_end_time", type: "datetime" },
        { name: "collection_start_time", type: "datetime" },
        {
          name: "collection_session_id",
          type: "integer",
          fk: { table: "collection_sessions", column: "id" },
        },
        {
          name: "shipment_leg_id",
          type: "integer",
          fk: { table: "shipment_legs", column: "id" },
        },
      ],
      pos: { x: 2596.0790998828115, y: 5632.026918398436 },
    },
    {
      name: "study_numbers",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "name", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 426.5581001757283, y: 4680.217199144648 },
    },
    {
      name: "subprocesses",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "customer_value", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "uuid", type: "uuid" },
        {
          name: "procedure_id",
          type: "integer",
          fk: { table: "procedures", column: "id" },
        },
        { name: "activity_id", type: "string" },
        { name: "name", type: "string" },
        { name: "execution_ids", type: "jsonb" },
        { name: "deleted_at", type: "datetime" },
      ],
      pos: { x: 3400.6267367578116, y: 5238.8655999609355 },
    },
    {
      name: "stage_configs",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "procedure_config_id",
          type: "integer",
          fk: { table: "procedure_configs", column: "id" },
        },
        {
          name: "shipment_leg_id",
          type: "integer",
          fk: { table: "shipment_legs", column: "id" },
        },
        { name: "scheduling_milestone", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "rescheduling_milestone", type: "string" },
        {
          name: "status_tracking_config_id",
          type: "integer",
          fk: { table: "status_tracking_configs", column: "id" },
        },
        { name: "position", type: "integer" },
        { name: "multi_shipments", type: "boolean" },
        { name: "schedulable", type: "boolean" },
        { name: "timezone", type: "string" },
        { name: "scheduling", type: "jsonb" },
        { name: "date_time_format_path", type: "string" },
        { name: "start_milestone", type: "jsonb" },
        { name: "end_milestone", type: "jsonb" },
      ],
      pos: { x: 3854.1654612636826, y: 3195.635049711398 },
    },
    {
      name: "step_configs",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "procedure_config_id",
          type: "integer",
          fk: { table: "procedure_configs", column: "id" },
        },
        { name: "name", type: "string" },
        { name: "schema", type: "jsonb" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "http_method", type: "string" },
        { name: "blocks", type: "jsonb" },
        { name: "ui_options", type: "jsonb" },
        { name: "perform_operations", type: "jsonb" },
        {
          name: "phase_config_id",
          type: "integer",
          fk: { table: "phase_configs", column: "id" },
        },
        { name: "phase_config_position", type: "integer" },
        { name: "signatures", type: "jsonb" },
        { name: "system_task", type: "boolean" },
        { name: "labels", type: "jsonb" },
        { name: "audit", type: "jsonb" },
        { name: "requires_reason_for_change", type: "boolean" },
        { name: "optional", type: "boolean" },
        { name: "require_signature", type: "jsonb" },
        { name: "alert_bar_messages", type: "jsonb" },
      ],
      pos: { x: 4171.7901648544685, y: 1020.5885207426904 },
    },
    {
      name: "status_tracking_configs",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "execution_context_id",
          type: "integer",
          fk: { table: "execution_contexts", column: "id" },
        },
        { name: "ordering_summary_page", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        {
          name: "config_deployment_id",
          type: "integer",
          fk: { table: "config_deployments", column: "id" },
        },
      ],
      pos: { x: 2583.739837398374, y: 3157.181439490176 },
    },
    {
      name: "translations",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "locale", type: "string" },
        { name: "key", type: "string" },
        { name: "value", type: "text" },
        { name: "is_proc", type: "boolean" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 5930.625185507811, y: 628.6759027734373 },
    },
    {
      name: "therapies",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "product_id",
          type: "integer",
          fk: { table: "products", column: "id" },
        },
        {
          name: "indication_id",
          type: "integer",
          fk: { table: "indications", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        {
          name: "study_number_id",
          type: "integer",
          fk: { table: "study_numbers", column: "id" },
        },
      ],
      pos: { x: 460.70467320884154, y: 4173.9836075118565 },
    },
    {
      name: "user_role_assignments",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "user_id",
          type: "integer",
          fk: { table: "users", column: "id" },
        },
        {
          name: "user_role_id",
          type: "integer",
          fk: { table: "user_roles", column: "id" },
        },
      ],
      pos: { x: 733.8754049161586, y: 5000 },
    },
    {
      name: "treatments",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "coi", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "cancelled_at", type: "datetime" },
        {
          name: "physician_id",
          type: "integer",
          fk: { table: "physicians", column: "id" },
        },
        { name: "lot_number", type: "string" },
        {
          name: "execution_context_id",
          type: "integer",
          fk: { table: "execution_contexts", column: "id" },
        },
        { name: "screening_date", type: "date" },
        {
          name: "patient_id",
          type: "integer",
          fk: { table: "patients", column: "id" },
        },
        { name: "schedules", type: "jsonb" },
        { name: "uuid", type: "uuid" },
        { name: "resource_identifier_id", type: "integer" },
      ],
      pos: { x: 4167.460274631738, y: 2816.79327533174 },
    },
    {
      name: "traceabilities",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "procedure_id",
          type: "integer",
          fk: { table: "procedures", column: "id" },
        },
        {
          name: "treatment_id",
          type: "integer",
          fk: { table: "treatments", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 2345.847405069243, y: 2556.6006058564 },
    },
    {
      name: "user_qualifications",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "user_role_id",
          type: "integer",
          fk: { table: "user_roles", column: "id" },
        },
        { name: "disqualify_reason", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "disqualified_at", type: "datetime" },
        {
          name: "product_id",
          type: "integer",
          fk: { table: "products", column: "id" },
        },
      ],
      pos: { x: 671.150489501953, y: 3721.9731306152335 },
    },
    {
      name: "variable_definitions",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "name", type: "string" },
        { name: "translation_key", type: "string" },
        { name: "fetcher", type: "string" },
        { name: "required_params", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "fetcher_type", type: "integer" },
      ],
      pos: { x: 5659.398305507811, y: 646.1437299609373 },
    },
    {
      name: "versions",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "item_type", type: "string" },
        { name: "item_id", type: "integer" },
        { name: "event", type: "string" },
        { name: "whodunnit", type: "string" },
        { name: "object", type: "jsonb" },
        { name: "object_changes", type: "jsonb" },
        { name: "created_at", type: "datetime" },
        { name: "object_details", type: "json" },
      ],
      pos: { x: 5363.28822550781, y: 663.2907212109374 },
    },
    {
      name: "vineti_custom_fields",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "data", type: "jsonb" },
        { name: "associate_type", type: "string" },
        { name: "associate_id", type: "integer" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 5923.160225507811, y: 364.6950929296874 },
    },
    {
      name: "vineti_custom_schemas",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "data", type: "jsonb" },
        { name: "associate_type", type: "string" },
        { name: "associate_id", type: "integer" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 5368.26486550781, y: 1000.1708096484373 },
    },
    {
      name: "user_roles",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "name", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "with_phi", type: "boolean" },
        { name: "is_sso", type: "boolean" },
        { name: "deleted_at", type: "datetime" },
        { name: "is_global", type: "boolean" },
        { name: "is_internal", type: "boolean" },
        { name: "uri", type: "text" },
      ],
      pos: { x: 1051.8325526953122, y: 3775.816363710936 },
    },
    {
      name: "users",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "provider", type: "string" },
        { name: "uid", type: "string" },
        { name: "email", type: "citext" },
        { name: "encrypted_password", type: "string" },
        { name: "tokens", type: "json" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "first_name", type: "string" },
        { name: "last_name", type: "string" },
        { name: "reset_password_token", type: "string" },
        { name: "password_changed_at", type: "datetime" },
        { name: "type", type: "string" },
        { name: "middle_name", type: "string" },
        { name: "country_code", type: "string" },
        { name: "phone_number", type: "string" },
        { name: "additional_country_code", type: "string" },
        { name: "additional_phone_number", type: "string" },
        { name: "preferred_language", type: "string" },
        { name: "belongs_to_all_institutions", type: "boolean" },
        { name: "deactivated_at", type: "datetime" },
        {
          name: "identity_provider_id",
          type: "integer",
          fk: { table: "identity_providers", column: "id" },
        },
        { name: "api_user", type: "boolean" },
      ],
      pos: { x: 1753.286186601562, y: 5500.145958398436 },
    },
    {
      name: "vineti_notifications_event_publishers",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "vineti_notifications_publisher_id", type: "integer" },
        { name: "vineti_notifications_event_id", type: "integer" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 6157.04559925781, y: 352.2029565234374 },
    },
    {
      name: "vineti_notifications_publisher_subscribers",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "vineti_notifications_publishers_id",
          type: "integer",
          fk: { table: "vineti_notifications_publishers", column: "id" },
        },
        {
          name: "vineti_notifications_subscribers_id",
          type: "integer",
          fk: { table: "vineti_notifications_subscribers", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 5797.148899658202, y: 5846.844917724608 },
    },
    {
      name: "vineti_notifications_event_transactions",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "transaction_id", type: "string" },
        { name: "payload", type: "jsonb" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        {
          name: "vineti_notifications_subscribers_id",
          type: "integer",
          fk: { table: "vineti_notifications_subscribers", column: "id" },
        },
        { name: "retries_count", type: "integer" },
        { name: "status", type: "enum" },
        { name: "response_code", type: "string" },
        { name: "response", type: "jsonb" },
        {
          name: "vineti_notifications_publishers_id",
          type: "integer",
          fk: { table: "vineti_notifications_publishers", column: "id" },
        },
        { name: "parent_transaction_id", type: "integer" },
        {
          name: "vineti_notifications_events_id",
          type: "integer",
          fk: { table: "vineti_notifications_events", column: "id" },
        },
      ],
      pos: { x: 5391.897040283202, y: 5191.725803466796 },
    },
    {
      name: "vineti_notifications_notification_email_logs",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "email_message", type: "json" },
        { name: "vineti_notifications_events_id", type: "integer" },
        { name: "vineti_notifications_subscribers_id", type: "integer" },
        { name: "vineti_notifications_templates_id", type: "integer" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "vineti_notifications_publishers_id", type: "integer" },
      ],
      pos: { x: 5298.591905507811, y: 89.48035511718746 },
    },
    {
      name: "vineti_notifications_notification_email_responses",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "type", type: "string" },
        { name: "response", type: "json" },
        {
          name: "vineti_notifications_notification_email_logs_id",
          type: "integer",
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 6127.194568007811, y: 116.63004269531247 },
    },
    {
      name: "vineti_notifications_events",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "name", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 5487.70422550781, y: 4957.692198398437 },
    },
    {
      name: "vineti_notifications_publishers",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "publisher_id", type: "string" },
        { name: "vineti_notifications_template_id", type: "integer" },
        { name: "payload_type", type: "integer" },
        { name: "active", type: "boolean" },
        { name: "data", type: "jsonb" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 5497.650823007811, y: 6102.312184335936 },
    },
    {
      name: "vineti_notifications_templates",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "template_id", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "default_variables", type: "json" },
        { name: "data", type: "json" },
        { name: "deeplinks", type: "json" },
      ],
      pos: { x: 5664.374945507811, y: 107.83499941406245 },
    },
    {
      name: "workflow_permissions",
      columns: [
        { name: "action", type: "string", pk: true },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 3552.769259033202, y: 581.1130437011717 },
    },
    {
      name: "execution_contexts",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "therapy_id",
          type: "integer",
          fk: { table: "therapies", column: "id" },
        },
        {
          name: "region_id",
          type: "integer",
          fk: { table: "regions", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        {
          name: "business_process_id",
          type: "integer",
          fk: { table: "business_processes", column: "id" },
        },
        { name: "display_name", type: "string" },
        { name: "unique_id", type: "string" },
        { name: "deleted_at", type: "datetime" },
      ],
      pos: { x: 2878.028799330962, y: 3539.2668106368565 },
    },
    {
      name: "user_roles_users",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "user_role_id",
          type: "integer",
          fk: { table: "user_roles", column: "id" },
        },
        {
          name: "user_id",
          type: "integer",
          fk: { table: "users", column: "id" },
        },
      ],
      pos: { x: 1665.7952860107418, y: 4467.704877685545 },
    },
    {
      name: "institutions",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "name", type: "string" },
        { name: "default_courier", type: "string" },
        { name: "primary_language", type: "string" },
        { name: "tissue_establishment_number", type: "string" },
        { name: "facility_identification_number", type: "string" },
        { name: "disqualify_reason", type: "string" },
        { name: "address_id", type: "integer" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "is_active", type: "boolean" },
        { name: "country_code", type: "string" },
        {
          name: "institution_type_id",
          type: "integer",
          fk: { table: "institution_types", column: "id" },
        },
        { name: "tenant_external_id", type: "string" },
        { name: "lead_time", type: "integer" },
        { name: "only_working_days", type: "boolean" },
        { name: "site_closes", type: "string" },
        { name: "site_opens", type: "string" },
        { name: "uuid", type: "uuid" },
        { name: "print_type", type: "integer" },
      ],
      pos: { x: 3548.773673039465, y: 3733.2263481326218 },
    },
    {
      name: "procedure_steps",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "procedure_id",
          type: "integer",
          fk: { table: "procedures", column: "id" },
        },
        { name: "data", type: "jsonb" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "completed_at", type: "datetime" },
        { name: "task_id", type: "string" },
        { name: "skipped_at", type: "datetime" },
        { name: "priority", type: "integer" },
        {
          name: "step_config_id",
          type: "integer",
          fk: { table: "step_configs", column: "id" },
        },
        { name: "locked_at", type: "datetime" },
        { name: "process_var_state", type: "jsonb" },
        { name: "validated_at", type: "datetime" },
        { name: "task_data", type: "jsonb" },
      ],
      pos: { x: 3783.197699652778, y: 1064.4988103933774 },
    },
    {
      name: "templates",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "label_definition_id",
          type: "integer",
          fk: { table: "label_definitions", column: "id" },
        },
        {
          name: "region_id",
          type: "integer",
          fk: { table: "regions", column: "id" },
        },
        { name: "language", type: "string" },
        { name: "active", type: "boolean" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "variable_map", type: "jsonb" },
      ],
      pos: { x: 1866.9908848151524, y: 1044.8541804440686 },
    },
    {
      name: "base_grants",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "user_role_id",
          type: "integer",
          fk: { table: "user_roles", column: "id" },
        },
        {
          name: "base_permission_id",
          type: "integer",
          fk: { table: "base_permissions", column: "id" },
        },
        { name: "deleted_at", type: "datetime" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 806.5039988778793, y: 3372.8997289972904 },
    },
    {
      name: "collections",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "treatment_id",
          type: "integer",
          fk: { table: "treatments", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 3402.1599353490483, y: 2315.981830297124 },
    },
    {
      name: "collection_sessions",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "collection_id",
          type: "integer",
          fk: { table: "collections", column: "id" },
        },
        { name: "patient_weight", type: "string" },
        { name: "day", type: "integer" },
        { name: "cbc_collected", type: "boolean" },
        { name: "apheresis_date", type: "date" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 2498.0914687076556, y: 3614.617737974255 },
    },
    {
      name: "role_contexts",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "user_role_id",
          type: "integer",
          fk: { table: "user_roles", column: "id" },
        },
        {
          name: "execution_context_id",
          type: "integer",
          fk: { table: "execution_contexts", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "deleted_at", type: "datetime" },
      ],
      pos: { x: 1014.0801820005505, y: 892.6738625296409 },
    },
    {
      name: "execution_contexts_physicians",
      columns: [
        {
          name: "execution_context_id",
          type: "integer",
          fk: { table: "execution_contexts", column: "id" },
        },
        {
          name: "physician_id",
          type: "integer",
          fk: { table: "physicians", column: "id" },
        },
      ],
      pos: { x: 3272.0826043023003, y: 3138.2055908037723 },
    },
    {
      name: "idp_user_roles",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "name", type: "string" },
        {
          name: "identity_provider_id",
          type: "integer",
          fk: { table: "identity_providers", column: "id" },
        },
        {
          name: "user_role_id",
          type: "integer",
          fk: { table: "user_roles", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 1187.531443856919, y: 4650.394263952405 },
    },
    {
      name: "phase_configs",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "procedure_config_id",
          type: "integer",
          fk: { table: "procedure_configs", column: "id" },
        },
        { name: "name", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        {
          name: "phase_key_id",
          type: "integer",
          fk: { table: "phase_keys", column: "id" },
        },
        { name: "hide_from_nav", type: "boolean" },
        { name: "parent_phase_config_id", type: "integer" },
        { name: "type", type: "string" },
        { name: "position", type: "integer" },
      ],
      pos: { x: 3443.3522625021174, y: 1511.6517353833208 },
    },
    {
      name: "procedure_dates",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "procedure_id",
          type: "integer",
          fk: { table: "procedures", column: "id" },
        },
        { name: "date", type: "date" },
        { name: "is_confirmed", type: "boolean" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "step_config_id", type: "integer" },
      ],
      pos: { x: 3999.5892355078113, y: 4365.471810585936 },
    },
    {
      name: "vineti_notifications_event_subscribers",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "vineti_notifications_events_id",
          type: "integer",
          fk: { table: "vineti_notifications_events", column: "id" },
        },
        {
          name: "vineti_notifications_subscribers_id",
          type: "integer",
          fk: { table: "vineti_notifications_subscribers", column: "id" },
        },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 5923.1602255078105, y: 4892.995878398437 },
    },
    {
      name: "vineti_notifications_subscribers",
      columns: [
        { name: "id", type: "integer", pk: true },
        { name: "vineti_notifications_templates_id", type: "integer" },
        { name: "subscriber_id", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        { name: "data", type: "json" },
        { name: "type", type: "string" },
        { name: "active", type: "boolean" },
        { name: "delayed_time", type: "integer" },
      ],
      pos: { x: 6254.09949550781, y: 5651.926568085936 },
    },
    {
      name: "workflow_grants",
      columns: [
        { name: "id", type: "integer", pk: true },
        {
          name: "step_config_id",
          type: "integer",
          fk: { table: "step_configs", column: "id" },
        },
        {
          name: "action",
          type: "string",
          fk: { table: "workflow_permissions", column: "action" },
        },
        { name: "deleted_at", type: "datetime" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
        {
          name: "role_context_id",
          type: "integer",
          fk: { table: "role_contexts", column: "id" },
        },
      ],
      pos: { x: 3949.854588826881, y: 564.8599802388803 },
    },
    {
      name: "schema_migrations",
      columns: [{ name: "version", type: "string", pk: true }],
      pos: { x: 5432.961185507811, y: 1599.7507562109372 },
    },
    {
      name: "ar_internal_metadata",
      columns: [
        { name: "key", type: "string", pk: true },
        { name: "value", type: "string" },
        { name: "created_at", type: "datetime" },
        { name: "updated_at", type: "datetime" },
      ],
      pos: { x: 5928.136865507811, y: 152.13176367187498 },
    },
  ],
  viewHeight: 8500,
  viewWidth: 8500,
};

export default schema;
