name: CD

on:
  create:
    tags:
      - v*

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - uses: microsoft/playwright-github-action@v1

      - run: sudo npm i -g yarn
      - run: yarn
      - run: yarn lint
      - run: yarn run test-headless
      - name: create env.json file
        run: >
          cat <<EOF >./env.json
            {
              "googleDrive": {
                "developerKey": "${{ secrets.GDRIVE_DEV_KEY }}",
                "clientId": "${{ secrets.GDRIVE_CLIENT_ID }}",
                "appId": "${{ secrets.GDRIVE_APP_ID }}"
              },
              "oneDrive": {
                "clientId": "${{ secrets.ONEDRIVE_CLIENT_ID }}"
              }
            }
          EOF
      - run: yarn run start-and-e2e
      - run: yarn run build-prod
      - name: Deploy to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@master
        with:
          source: "dist"
          storageZoneName: "dbgrapher"
          accessKey: "${{ secrets.BUNNY_CDN_STORAGE_KEY }}"
