name: Deploy

on:
  create:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: create env.json file
        run: >
          cat <<EOF >./apps/main/env.json
            {
              "googleDrive": {
                "developerKey": "${{ secrets.GDRIVE_DEV_KEY }}",
                "clientId": "${{ secrets.GDRIVE_CLIENT_ID }}",
                "appId": "${{ secrets.GDRIVE_APP_ID }}"
              },
              "oneDrive": {
                "clientId": "${{ secrets.ONEDRIVE_CLIENT_ID }}"
              }
            }
          EOF
      - run: cd apps/main && npm run build
      - name: Deploy to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@v1.1.1
        with:
          source: "apps/main/dist"
          storageZoneName: "${{ secrets.BUNNY_CDN_STORAGE_NAME }}"
          accessKey: "${{ secrets.BUNNY_CDN_STORAGE_KEY }}"
          pullZoneId: "${{ secrets.ZONE_ID }}"
          pullZoneAccessKey: "${{ secrets.PULL_ZONE_KEY }}"
          remove: "true"
          purge: "true"
