name: Deploy

on:
  create:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run build
      - name: Deploy to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@v1.1.1
        with:
          source: "apps/main/dist"
          storageZoneName: "${{ secrets.BUNNY_CDN_STORAGE_NAME }}"
          accessKey: "${{ secrets.BUNNY_CDN_STORAGE_KEY }}"
          pullZoneId: "${{ secrets.BUNNY_CDN_ZONE_ID }}"
          pullZoneAccessKey: "${{ secrets.BUNNY_CDN_PULL_ZONE_KEY }}"
          remove: "true"
          purge: "true"
